package com.wsteam.wandscape.core.road;

/**
 * A placement decision for a single road template in the world.
 * Generated by {@link TemplateExpander}, consumed by the engine layer.
 *
 * @param templateId maps to {@link TemplateMeta#id}
 * @param x          world X placement (template origin)
 * @param z          world Z placement (template origin)
 * @param rotation   CCW 90° rotation steps (0=NONE, 1=90°, 2=180°, 3=270°)
 */
public record TemplatePlacement(
        String templateId,
        int x,
        int z,
        int rotation) {

    /** MC rotation name for logging. */
    public String rotationName() {
        return switch (rotation & 3) {
            case 0 -> "NONE";
            case 1 -> "CLOCKWISE_90";
            case 2 -> "CLOCKWISE_180";
            case 3 -> "COUNTERCLOCKWISE_90";
            default -> "NONE";
        };
    }
}
