package com.wsteam.wandscape.engine.road;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.slf4j.Logger;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.mojang.logging.LogUtils;
import com.wsteam.wandscape.core.road.XZPoint;

import net.minecraft.core.BlockPos;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraft.world.level.levelgen.structure.BoundingBox;

/**
 * Builds road tile data from L-shaped path coordinates.
 *
 * <p>V1 path generation + V3 aesthetics:
 * <ul>
 *   <li>3-wide roads (configurable via {@code road.default_width})</li>
 *   <li>Terrain surface matching via {@link Heightmap.Types#WORLD_SURFACE}</li>
 *   <li>Vanilla-style block variation (worn path, water bridges, stone transition)</li>
 * </ul>
 *
 * <p>Output tiles feed into {@code road:build_segment} for NPC construction.
 */
public final class RoadBuilder {

    private static final Logger LOGGER = LogUtils.getLogger();

    private RoadBuilder() {}

    /**
     * Build a JsonArray of tiles ready for the road:build_segment blueprint.
     * Each tile is: {@code {"pos": [x, y, z], "block": "minecraft:..."}}.
     *
     * <p>Roads are multi-wide: center tile + perpendicular offset tiles on each side.
     * Block selection uses vanilla-style rules: water → planks bridge,
     * grass → worn patches, stone → cobblestone transition.
     *
     * @param level          the server level
     * @param path           ordered XZ path points (center line, already deduped)
     * @param tier           road tier name (e.g. "dirt")
     * @param buildingBounds bounding boxes of all buildings — tiles inside are skipped
     * @param occupiedTiles  mutable set of XZ positions already claimed by other edges;
     *                       updated in-place with tiles generated by this call
     */
    public static JsonArray buildTiles(Level level, List<XZPoint> path,
                                        String tier,
                                        Collection<BoundingBox> buildingBounds,
                                        Set<XZPoint> occupiedTiles) {
        RoadConfig config = RoadConfig.getInstance();
        String defaultBlock = config.getDefaultBlock(tier);
        int halfWidth = config.getDefaultWidth() / 2;

        JsonArray tiles = new JsonArray();
        for (int i = 0; i < path.size(); i++) {
            XZPoint p = path.get(i);

            // Determine perpendicular offset from travel direction
            int perpDx = 0, perpDz = 0;
            if (path.size() == 1) {
                perpDz = 1;
            } else {
                boolean moveX = false, moveZ = false;
                if (i > 0) {
                    XZPoint prev = path.get(i - 1);
                    if (prev.x() != p.x()) moveX = true;
                    if (prev.z() != p.z()) moveZ = true;
                }
                if (i < path.size() - 1) {
                    XZPoint next = path.get(i + 1);
                    if (next.x() != p.x()) moveX = true;
                    if (next.z() != p.z()) moveZ = true;
                }
                if (moveX && !moveZ) {
                    perpDz = 1; // X segment → offset Z (perpendicular)
                } else if (moveZ && !moveX) {
                    perpDx = 1; // Z segment → offset X (perpendicular)
                }
                // If both moveX and moveZ (corner), prefer perpendicular to dominant axis
            }

            // Generate width tiles: center + symmetric perpendicular offsets
            List<Integer> offsets = new ArrayList<>();
            for (int w = -halfWidth; w <= halfWidth; w++) {
                offsets.add(w);
            }

            for (int w : offsets) {
                int tx = p.x() + perpDx * w;
                int tz = p.z() + perpDz * w;

                // Skip tiles inside building bounding boxes
                if (insideAnyBuilding(tx, tz, buildingBounds)) continue;

                // Skip tiles whose XZ is already claimed
                XZPoint tileXz = new XZPoint(tx, tz);
                if (occupiedTiles.contains(tileXz)) continue;

                // Terrain surface matching (vanilla GravityProcessor style)
                int surfaceY = level.getHeight(Heightmap.Types.WORLD_SURFACE, tx, tz);
                int roadY = surfaceY - 1;
                BlockPos pos = new BlockPos(tx, roadY, tz);

                // Skip fluid positions (water/lava) — can't build road on water
                BlockState state = level.getBlockState(pos);
                if (!state.getFluidState().isEmpty()) continue;

                // Apply vanilla-style block variation
                String block = applyVariation(level, pos, defaultBlock);

                occupiedTiles.add(tileXz);

                JsonObject tile = new JsonObject();
                JsonArray posArr = new JsonArray();
                posArr.add(pos.getX());
                posArr.add(pos.getY());
                posArr.add(pos.getZ());
                tile.add("pos", posArr);
                tile.addProperty("block", block);
                tiles.add(tile);
            }
        }

        return tiles;
    }

    /**
     * Extract XZ points from tile JSON for occupancy tracking.
     */
    public static Set<XZPoint> extractXZ(JsonArray tiles) {
        Set<XZPoint> result = new HashSet<>();
        for (int i = 0; i < tiles.size(); i++) {
            var t = tiles.get(i).getAsJsonObject().getAsJsonArray("pos");
            result.add(new XZPoint(t.get(0).getAsInt(), t.get(2).getAsInt()));
        }
        return result;
    }

    // ---- Vanilla-style block variation ----

    /**
     * Apply worn-path block variation matching vanilla STREET_PLAINS rules.
     *
     * <p>Rules:
     * <ul>
     *   <li>Water underneath → oak planks (bridge)</li>
     *   <li>Grass → 85% dirt_path, 15% grass_block (worn patches)</li>
     *   <li>Stone/cobblestone → cobblestone (rocky path)</li>
     *   <li>Default → original block</li>
     * </ul>
     */
    static String applyVariation(Level level, BlockPos roadPos, String blockId) {
        if (!"minecraft:dirt_path".equals(blockId)) return blockId;

        BlockPos below = roadPos.below();
        BlockState ground = level.getBlockState(below);

        // Water underneath → wood planks (bridge)
        if (!ground.getFluidState().isEmpty()) {
            return "minecraft:oak_planks";
        }

        String groundName = ground.getBlock().builtInRegistryHolder()
                .key().location().toString();

        // Grass → 85% dirt_path, 15% grass_block (worn patches)
        if ("minecraft:grass_block".equals(groundName)) {
            long h = ((long) roadPos.getX() * 31 + roadPos.getZ()) ^ 0x3A7F;
            if (Math.abs(h % 100) < 15) {
                return "minecraft:grass_block";
            }
        }

        // Stone/cobblestone → cobblestone (rocky path)
        if ("minecraft:stone".equals(groundName)
                || "minecraft:cobblestone".equals(groundName)) {
            return "minecraft:cobblestone";
        }

        return blockId;
    }

    // ---- Helpers ----

    private static boolean insideAnyBuilding(int x, int z,
                                              Collection<BoundingBox> boxes) {
        for (BoundingBox box : boxes) {
            if (x >= box.minX() && x <= box.maxX()
                    && z >= box.minZ() && z <= box.maxZ()) {
                return true;
            }
        }
        return false;
    }
}
