package org.magiccolony.core.task;

import org.magiccolony.core.op.AtomicOp;

import java.util.Collections;
import java.util.List;

/**
 * A static blueprint of operations that form a task.
 * Generated by a TaskCompiler from a TaskRequest.
 */
public record TaskSequence(List<AtomicOp> steps, String label) {

    public TaskSequence {
        steps = List.copyOf(steps);
    }

    public int size() {
        return steps.size();
    }

    /** True if stepIndex has reached the end. */
    public boolean isComplete(int stepIndex) {
        return stepIndex >= steps.size();
    }

    public AtomicOp get(int index) {
        return steps.get(index);
    }

    public static TaskSequence of(String label, AtomicOp... steps) {
        return new TaskSequence(List.of(steps), label);
    }
}
